# Generated by Django 4.1.3 on 2023-05-31 07:16

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('body', ckeditor.fields.RichTextField()),
                ('category', models.CharField(choices=[('Tanks', 'Танки'), ('Frail', 'Хилы'), ('DD', 'ДД'), ('Merchants', 'Торговцы'), ('Guild Masters', 'Гилдмастеры'), ('Quest Givers', 'Квестгиверы'), ('Blacksmiths', 'Кузнецы'), ('Tanners', 'Кожевники'), ('Potion Makers', 'Зельевары'), ('Spell Masters', 'Мастера заклинаний')], max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accept', 'Принять'), ('Delete', 'Удалить')], max_length=10, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
